exper_name: "shihua molecule optimization"
description: "optimize the molecule according to the constraints"
save_dir: "/root/nian/mollm_results/shihua_mol"
save_suffix: "new_score_constraint5"

cal_div: True
resume: False
early_stopping: False
model:
  name: zgca,gpt-5-minimal  #  gemini-2.5-flash-nothinking  #,gemini-2.5-flash-nothinking     gpt-4-0125-preview  gpt-4o-2024-05-13
  # name2: zgca,gpt-4o-2024-05-13
  prompt_module: Prompt
  #temperature: 1.
  experience_prob: 0.5
  crossover_prob: 0.8
  mutation_prob: 0.2 
  explore_prob: 0. 
use_au: False  # If True, this will use au model, set to false if you only want to use one LLM

goals: [molecular_weight,sa_score,homo_lumo_gap_au,dipole_moment_debye]
optimization_direction: [min,min,min,min]
prompt_info_path: /root/nian/MOLLM/problem/shihua_mol/prompt_info.yaml
### Important ###
evalutor_path: problem.shihua_mol.evaluator

optimization: 
  pop_size: 2
  eval_budget: 5000



