exper_name: "0.5 exp, add a sentence in crossover, best_f 0.5 pareto 0.5, with description, and other description in above, linear crossover prob:0.2 + len(self.history_moles) / self.budget * 0.6"
save_dir: "/home/v-nianran/src/results/material"
save_suffix: "best10_focus_redu"

material: True

model:
  name: chatgpt
  prompt_module: Prompt
  experience_prob: 0.5
  crossover_prob: 0.5
  mutation_prob: 0.5
  explore_prob: 0

goals: [smarts_filter,logs,reduction_potential,sa]

optimization: 
  pop_size: 50
  eval_budget: 5000
  ngen: 5

dataset:
  path: "/home/v-nianran/src/MOLLM/data/yue300.json"

init_datset: ZINC
