exper_name: "7.8, with genetic_gfn as au model, start inserting 30 offspring in each generation after oracle calls > 0, and ga inside gfn added"
description: "32 gfn for main and au, use canonical=True"
save_dir: "/home/hp/src/mollm_results/coevol"
save_suffix: "0708_add_ga_onlygenetic"
initial_pop: "random1" # best100, worst100, random1 ~ 5

material: False
model:
  name: zgca,gemini-2.5-flash-preview-04-17-nothinking  #,gemini-2.5-flash-preview-04-17-nothinking     gpt-4-0125-preview  gpt-4o-2024-05-13
  prompt_module: Prompt
  experience_prob: 0.
  crossover_prob: 0.8
  mutation_prob: 0.2 
  explore_prob: 0. 
use_au: True

goals: [sa,drd2,qed,gsk3b,jnk3]

optimization: 
  pop_size: 50
  eval_budget: 5000
  ngen: 5

dataset:
  path: "/home/hp/src/MOLLM/data/goals5.json"

init_datset: ZINC



