exper_name: "0.5 experience in middle without mols"
save_dir: "/home/hp/src/mollm_results/pmo"
save_suffix: "0507_exp0.5_random1"
initial_pop: "random1" # best100, worst100, random1 ~ 5

material: False
model:
  name: zhongzhuan,gpt-4o-2024-05-13
  prompt_module: Prompt
  experience_prob: 0.5
  crossover_prob: 0.8
  mutation_prob: 0.2 
  explore_prob: 0. 


goals: [sa,drd2,qed,gsk3b,jnk3]

optimization: 
  pop_size: 50
  eval_budget: 10000
  ngen: 5

dataset:
  path: "/home/hp/src/MOLLM/data/goals5.json"

init_datset: ZINC



