model:
  name: chatgpt
  prompt_module: Prompt

goals: [sa,drd2,qed,gsk3b,jnk3]

optimization: 
  pop_size: 20
  eval_budget: 10000
  ngen: 5

dataset:
  path: "/home/v-nianran/src/MOLLM/data/goals5.json"

init_datset: ZINC

save_dir: "/home/v-nianran/src/results"
save_suffix: "goals5"
