
exper_name: "SACS Jacket Optimization - Code Block Generation"
description: "Optimizing SACS structure using direct code block generation by LLM."
save_dir: "/root/src/mollm_results/sacs"
save_suffix: "sacs_block_gen"

resume: False

model:
  name: zgca,gemini-2.5-flash-nothinking  #,gemini-2.5-flash-nothinking     gpt-4-0125-preview  gpt-4o-2024-05-13
  # name2: zgca,gpt-4o-2024-05-13
  prompt_module: Prompt
  experience_prob: 0.5
  crossover_prob: 0.8
  mutation_prob: 0.2
  explore_prob: 0
use_au: False

# --- Key Problem Definitions ---
goals: [weight, uc, fatigue]
optimization_direction: [min, min, max]

prompt_info_path: ./problem/sacs/sacs.yaml
evalutor_path: problem.sacs.evaluator

sacs:
  project_path: "/mnt/d/Python project/sacs_llm/demo06_project/Demo06" # IMPORTANT: Set this to your actual SACS project path

  optimizable_blocks:
    - "GRUP LG1"
    - "GRUP LG2"
    - "GRUP LG3"
    - "GRUP LG4"
    - "GRUP T01"
    - "GRUP T02"
    - "GRUP T03"
    - "PGRUP P01"

optimization:
  pop_size: 40
  eval_budget: 200
